GET localhost:5000/books

###

GET localhost:5000/books/1

###

POST localhost:5000/books
Content-Type: application/json

{
  "title": "Title 10",
  "author": "Author 1",
  "publisher": "Publisher 1",
  "edition": 1,
  "isbn": "978-65-89999-01-3",
  "price": 19.9,
  "publishDate": "2022-10-25"
}

###

PUT localhost:5000/books/1
Content-Type: application/json

{
  "title": "Title 100",
  "author": "Author 110",
  "publisher": "Publisher 1",
  "edition": 1,
  "isbn": "978-65-89999-01-3",
  "price": 19.9,
  "publishDate": "2022-10-25"
}

###

DELETE localhost:5000/books/1
