@AppHostAddress = http://localhost:5000

GET {{AppHostAddress}}/categories
Accept: application/json

###

GET {{AppHostAddress}}/categories/3
Accept: application/json

###

POST {{AppHostAddress}}/categories
Content-Type: application/json

{
  "name": "Category 4",
  "description": "Description 4"
}

###

PUT {{AppHostAddress}}/categories/4
Content-Type: application/json

{
  "name": "Category 45",
  "description": "Description 45"
}

###

DELETE {{AppHostAddress}}/categories/4
Accept: application/json

###