@AppHostAddress = http://localhost:5000

GET {{AppHostAddress}}/categories
Accept: application/json

###

GET {{AppHostAddress}}/categories/1
Accept: application/json

###

POST {{AppHostAddress}}/categories
Content-Type: application/json

{
  "name": "Category 1",
  "description": "Description 1"
}

###

PUT {{AppHostAddress}}/categories/1
Content-Type: application/json

{
  "name": "Category 1",
  "description": "New Description"
}

###

DELETE {{AppHostAddress}}/categories/1
Accept: application/json

###