@baseUrl = http://localhost:5000

GET {{baseUrl}}/authors

###

GET {{baseUrl}}/authors/1

###

POST {{baseUrl}}/authors
Content-Type: application/json

{
  "name": "Author 1"
}

###

PUT {{baseUrl}}/authors/1
Content-Type: application/json

{
  "name": "Author 1"
}

###

DELETE {{baseUrl}}/authors/1