@baseUrl = http://localhost:5000

GET {{baseUrl}}/books

###

GET {{baseUrl}}/books/1

###

POST {{baseUrl}}/books
Content-Type: application/json

{
  "title": "Title 40",
  "authorId": 1,
  "publisherId": 1,
  "edition": 1,
  "isbn": "978-65-89999-01-3",
  "price": 19.9,
  "publishDate": "2022-10-25"
}

###

PUT {{baseUrl}}/books/1
Content-Type: application/json

{
  "title": "Title 100",
  "authorId": 1,
  "publisherId": 2,
  "edition": 1,
  "isbn": "978-65-89999-01-3",
  "price": 19.9,
  "publishDate": "2022-10-25"
}

###

DELETE {{baseUrl}}/books/1
