@baseUrl = http://localhost:5000

GET {{baseUrl}}/publishers

###

GET {{baseUrl}}/publishers/1

###

POST {{baseUrl}}/publishers
Content-Type: application/json

{
  "name": "Publisher 1"
}

###

PUT {{baseUrl}}/publishers/1
Content-Type: application/json

{
  "name": "Publisher 10"
}

###

DELETE {{baseUrl}}/publishers/1