@baseUrl = http://localhost:5000

GET {{baseUrl}}/games

###

GET {{baseUrl}}/games/1

###

POST {{baseUrl}}/games
Content-Type: application/json

{
  "name": "Minecraft",
  "genreId": 5,
  "price": 19.99,
  "releaseDate": "2011-11-18"
}

###

PUT {{baseUrl}}/games/1
Content-Type: application/json

{
  "name": "Street Fighter II Turbo",
  "genreId": 1,
  "price": 9.99,
  "releaseDate": "1992-07-15"
}

###

DELETE {{baseUrl}}/games/4