@baseUrl = http://localhost:5000

GET {{baseUrl}}/todoList

###

GET {{baseUrl}}/todoList/1

###

POST {{baseUrl}}/todoList
Content-Type: application/json

{
  "description": "Go to the movies"
}

###

PUT {{baseUrl}}/todoList/1
Content-Type: application/json

{
  "description": "Go to the mall",
  "isCompleted": true
}

###

DELETE {{baseUrl}}/todoList/1